---
title: "Reading Group"
---
<head>
<style>
    details summary {
      font-size: 20px;
      cursor: pointer; 
      margin-left:30px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 10px 0; 
    }
    th, td  {
        border: 1px solid #ccc;
        border-left:0;
        border-right:0;
        font-size: 17px;
        padding: 8px;
        text-align: left;
        vertical-align: middle;
    }
    li {
        font-size: 17px;
    }
    /* ul {
        margin-top: 0px;
        margin-left:20px;
    } */
</style>
</head>

<!-- ## 2024

### May 15

#### Forecasting
- Large Language Models are Few-Shot Health Learners
- Leveraging Language Foundation Models for Human Mobility Forecasting

#### Health
- Large Language Models are Few-Shot Health Learners
- ``It Is a Moving Process'': Understanding the Evolution of Explainability Needs of Clinicians in Pulmonary Medicine

#### Active Learning + Spatio temporal
- Deep Bayesian Active Learning for Accelerating Stochastic Simulation
- Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets
- Deep Distributed Fusion Network for Air Quality Prediction

#### Object Detection + Sustainable Vision
- You Only Look Once: Unified, Real-Time Object Detection
- Generating Interpretable Poverty Maps using Object Detection in Satellite Images
 -->
<body>

<details>
<summary style ="font-size: 25px;margin-left:0px;">Pending Reading List</summary>
<div style="margin-left:30px;">
<h4>Health</h4> 
<ul style="margin: 0px;">
    <li>Leveraging Language Foundation Models for Human Mobility Forecasting</li>
    <li>"It Is a Moving Process’’: Understanding the Evolution of Explainability Needs of Clinicians in Pulmonary Medicine</li>
</ul>
<h4>Active Learning</h4>
<ul style="margin: 0px;">
    <li>Deep Bayesian Active Learning for Accelerating Stochastic Simulation</li>
    <li>Active Learning on a Budget: Opposite Strategies Suit High and Low Budgets</li>
</ul>
<h4>Spatio temporal</h4>
<ul style="margin: 0px;">
    <li>Deep Distributed Fusion Network for Air Quality Prediction</li>
    <li>Generating Interpretable Poverty Maps using Object Detection in Satellite Images</li>
</ul>
<h4>Object Detection</h4>
<ul style="margin: 0px;">
    <li>None</li>
</ul>
</div>
</details>


## 2024

### June

<table>
    <thead>
        <tr>
            <th style="width: 20%;">Category</th>
            <th style="width: 20%;">Presenter/Date</th>
            <th style="width: 60%;">Topics</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Self Supervised Learning</td>
            <td>Rishabh Mondal<br>[21-Jun-2024]</td>
            <td><a href="https://openaccess.thecvf.com/content/CVPR2024/papers/Chen_Low-Res_Leads_the_Way_Improving_Generalization_for_Super-Resolution_by_Self-Supervised_CVPR_2024_paper.pdf">Low-Res Leads the Way: Improving Generalization for Super-Resolution by Self-Supervised Learning</a></td>
        </tr>
        <tr>
            <td>Air Quality</td>
            <td>Devodita Chakravarty<br>[20-Jun-2024]</td>
            <td><a href="https://www.sciencedirect.com/science/article/pii/S0034425723001608?ref=pdf_download&fr=RR-2&rr=898b95770ecc8af9">Predicting air quality via multimodal AI and satellite imagery</a></td>
        </tr>
        <tr>
            <td>Health Sensing</td>
            <td>Mohit Maurya<br>[19-Jun-2024]</td>
            <td><a href="https://dl.acm.org/doi/10.1145/3659607">BreathPro: Monitoring Breathing Mode during Running with Earables</a></td>
        </tr>
        <tr>
            <td rowspan="2">Mock Defence</td>
            <td>Suraj Jaiswal<br>[17-Jun-2024]</td>
            <td>Large Scale Brick Kiln Detection and Compliance Monitoring from Satellite Imagery</td>
        </tr>
        <tr>
            <td>Ayush Shrivastava<br>[11-Jun-2024]</td>
            <td>Sensing Respiration and Sleep Apnea using Thermal Imaging in Real World Conditions</td>
        </tr>
        <tr>
            <td>Active Learning</td>
            <td>Shataxi Dubey<br>[13-Jun-2024]</td>
            <td><a href ="https://portalrecerca.uab.cat/en/publications/active-learning-for-deep-detection-neural-networks">Active Learning for Deep detection neural networks</a></td>
        </tr>
        <tr>
                <td rowspan="2">Object Detection</td>
                <td>Shiva Singh<br>[12-Jun-2024]</td>
                <td><a href="https://jmlr.org/papers/volume17/15-239/15-239.pdf">Domain Adversarial Training of Neural Networks</a></td>
        </tr>
        <tr>
                <td>Vansh Jani<br>[12-Jun-2024]</td>
                <td><a href="https://www3.cs.stonybrook.edu/~minhhoai/papers/Self-Supervised_Scene_Adaptation_CVPR23.pdf">Object Detection with Self-supervised Scene Adaptation</a></td>
        </tr>
    </tbody>
</table>


### May
<table>
    <thead>
        <tr>
            <th style="width: 20%;">Category</th>
            <th style="width: 20%;">Presenter</th>
            <th style="width: 60%;">Topics</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="2">Health</td>
            <td rowspan="2">Rishiraj Adhikary<br>[23-May-2024]</td>
            <td><a href="https://deepai.org/publication/large-language-models-are-few-shot-health-learners">Large Language Models are Few-Shot Health Learners</a></td>
        </tr>
        <tr>
            <td>[Thesis Presentaion] Exploring Health and Wellness through Respiratory Sensing</td>
        </tr>
        <tr>
            <td>Large Language Models</td>
            <td>Sajay Raj and <br>Muhammad Zaid<br>[20-May-2024]</td>
            <td><a href="https://labelbox.com/guides/zero-shot-learning-few-shot-learning-fine-tuning/">Zero-shot, Few-shot and Finetuning LLMs today for a few tasks</a></td>
        </tr>
        <tr>
            <td>Object Detection</td>
            <td>Vansh Jani<br>[17-May-2024]</td>
            <td><a href="https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7780460">You Only Look Once: Unified, Real-Time Object Detection</a></td>
        </tr>
    </tbody>
</table>

</body>
