
---
title: From Chemical Engineer to AI Researcher - My Pathway Through Sustainability Lab
author: "Aditi Agarwal"
date: "2024-05-19"
---

**Abstract**

I am Aditi Agarwal, I have graduated IIT Gandhinagar as a Chemical Engineer with a Minors in Computer Science. I am currently working with Google DeepMind as a PreDoctoral Researcher. This page summarizes the 3 semesters I have worked with Sustainability Lab and how the experiences have completely changed my career trajectory and views about research!

**Keywords: Sustainability Lab, 11/10 Recommended, Real Flavour of Research, Best Mentor**

**Introduction**

It would be an understatement to say that Sustainability Lab has completely changed the trajectory of my career. I had dreamt of being a Software Engineer from the age of 8. Computers were and are my Roman Empire, and younger me was always enticed by the idea of doing a job where I had to spend my entire day on a computer. How fascinating!

Coming to IIT Gandhinagar as a Chemical Engineering student, I always knew I would have to step the extra mile to achieve my goals. However, my journey was sweetened and streamlined by joining the Sustainability Lab and working under the guidance of Prof. Nipun Batra!

**Neural Network Newbie**

I joined the Sustainability Lab in my 6th semester. I remember the first time I visited Prof. Batra’s office, he asked me what I was interested in working on, and I naively mentioned that I wanted to build my own Neural Networks rather than using pre-trained models. Mind you, I had worked with two startups until then as a CV intern and an ML intern, but while I was able to ship code to production using fast.ai, play around with data, etc., I never had a core understanding of what Machine Learning really is. This is where the Sustainability Lab helped me.

**A class I did not sleep in**

I was also taking the coveted ES 654 course with Professor Batra at the time. I remember the first class of the course. Probably the only class in the entire duration of my BTech where I had a smile on my face throughout. Prof. Batra was showing us some videos on what AI is. I remember seeing a video of Amazon Go and being so fascinated and excited to finally learn a course because I wanted to and not because it was a graduation requirement. Simultaneously working with Sir in the lab, I remember, in the initial days, I took 3 weeks to correctly train a heteroskedastic MLP in Pytorch on a basic dataset. The catch was only to change the loss function, but my lack of understanding of core ML concepts led to me making numerous mistakes each time. What I really enjoyed during these three weeks was the fact that every time in the weekly meeting, Nipun Sir explained the loss function until I finally got it right. Then, I was extremely impatient, waiting every week to be given a “meatier” exercise rather than training a simple MLP. It is now that I realize how important this activity was for me. The latter half of the semester was smoother, and I was given a chance to play around with real-world data as well. That semester marked my first experience as a researcher as I also presented a poster at the UGRS.

**Brick by Brick**

In my seventh semester, in the last few days of summer, Prof. Batra offered me the brick kilns project. This was the project that quite literally changed my career trajectory and defined my interests. The project aimed to use satellite data for the detection of brick kilns across India. The novelty lay in using techniques to minimize the data and maximize the metrics of the model. We were working on a rather challenging deadline of submitting a paper to a sub-track in AAAI’23 in a matter of 20 days. Every day, we had meetings in the office with Sir and we would spend hours in the AI lab, getting the code to work and receiving outcomes. This was my first experience writing a manuscript and also learning how to present one’s work. Mind you, I have always been into writing and reading fiction. I thought of academic writing as “boring and flavorless.” It was when the process of writing the manuscript started that I realized how important building a story is in a research paper. On 16 August 2023, at 1705 hours, we ended up submitting the manuscript. It did not matter that it was rejected. But those 20 days gave me the real flavor of research.

Working on a project that directly impacts numerous people, their livelihoods, and the climate fueled my intent to pursue a career in research. We continued working on the project throughout the semester. In my final semester, in a spur of the moment, I decided to take up extra credits and work on a project to develop a screening system for mental health issues in students. This was a project done in collaboration with another lab in the institute. Again, this turned out to be an interesting experience because we experimented with multiple techniques in the beginning and ended up pivoting our approach to make our results more explainable and ethical.

**The Prof. Batra Effect**

What distinguishes the Sustainability Lab is Nipun Sir’s commitment to helping each and every student reach their full potential. As a Chemical Engineering student working in Computer Science and specifically in AI, I have more often than not had the feeling of not being good enough. Working with Prof. Batra has instilled a confidence in me that what matters is my work and not my branch. I owe my current position as a Pre-Doctoral Researcher at Google DeepMind to Prof. Batra for his invaluable guidance throughout. I remember running to him for interview help, preparation tips, how to write an SOP, tips on my personal website, and the LORs and personal notes. It was him who told me about the program at first and motivated me to apply for the same, not letting my doubts get the better of me. He always mentions, “Don’t self-reject.”

I have always been an individual who focuses on getting results. My definition of results meant something positive and quantitative, a 5% boost in accuracy, or a reduction in loss. Anything less would annoy me and make me feel as if whatever I did in the week was futile. Mind you, Prof. Batra too is an individual who focuses on the results. But the primary difference here is his ideology about the result. For him, results mean the insights and conclusions that one draws from any task or activity. I have seen the transition in the way I now present my work. It is always introduced by the motivation and the “why.” Sometimes I don’t even have results, but I am more often than not content with what I am presenting. This ideological change was again part of the Sustainability Lab experience.

**Lab Legends**

Prof. Batra bid us all farewell with a book and a personalized note. Coincidentally, it is also my favorite book, “Deep Work” by Cal Newport (a book I have annotated heavily and try to apply at least 10% of it in my life). Nipun Sir’s sense of humor and jovial energy always made me look forward to the weekly meetings. I remember, when his office was moved to the new Academic Block, he sent us a video guide as to how one can reach his office. Another fond memory I have is him sending me the contact details of a doctor in Gandhinagar because he got to know that I had injured my hand playing squash. I have countless such anecdotes that show his genuine care and concern towards his students. My journey at SL would be incomplete without mentioning all the amazing colleagues who became friends: Suraj Jaiswal, Madhav Kanda, Dhruv Patel, Rishabh Mondal, Zeel Patel, Aadesh Desai, Eshan Gujarathi, Saagar Parikh. The lab dinner at Akshardham (I will not spoil the reason as to why we go to Akshardham). Little celebrations we have at the lab and fun conversations that take place before every meeting have left a positive imprint on me.

**Consider this little article as my LOR to the Sustainability Lab to whomever it may concern 😊** 

This lab holds a very integral part of my BTech, and if you are an IITGn student who’s thinking about doing an internship/project with somebody, I would 11/10 recommend you to work at the Sustainability Lab.